# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for LitManager Backend (FastAPI Server)"""

block_cipher = None

a = Analysis(
    ['backend/app/main.py'],
    pathex=['backend'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'app',
        'app.config',
        'app.database',
        'app.security',
        'app.utils',
        'app.constants',
        'app.models',
        'app.models.model',
        'app.schemas',
        'app.schemas.model',
        'app.routers',
        'app.routers.admins',
        'app.routers.agent',
        'app.routers.audit',
        'app.routers.borrowing',
        'app.routers.conversations',
        'app.routers.copies',
        'app.routers.export',
        'app.routers.literature',
        'app.routers.models',
        'app.routers.notifications',
        'app.routers.readers',
        'app.routers.reservations',
        'app.routers.statistics',
        'app.routers.system',
        'app.services',
        'app.services.db_agent',
        'app.services.isbn_lookup',
        'app.services.model_service',
        'app.services.web_search',
        'uvicorn',
        'uvicorn.main',
        'uvicorn.config',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        'fastapi',
        'fastapi.middleware',
        'fastapi.middleware.cors',
        'sqlalchemy',
        'sqlalchemy.ext.asyncio',
        'aiosqlite',
        'pydantic',
        'pydantic_settings',
        'passlib',
        'passlib.context',
        'passlib.hash',
        'passlib.utils',
        'passlib.utils.handlers',
        'passlib.crypto.digest',
        'bcrypt',
        'jose',
        'jose.jwt',
        'openpyxl',
        'matplotlib',
        'httpx',
    ],
    excludes=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='LitManagerServer',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
